#!/bin/sh
grep -E '<td>.*<\/td>' |
#remove everything except for <td>word</td>

sed '/<td><\/td>/d' |
#remove  <td>empty</td>

sed 's/<td>\(.*\)<\/td>/\1/g' |
#remove tag <td> and tag </td>

sed -n 2~2p |
#Extract only the Hawaiian words

sed 's/<u>\(.\)<\/u>/\1/g' |
#delet <u> </u> within a word

tr , '\n' |
#replace the comma with newline

sed 's/^[ \t]*//' |
#delete all the leading space

tr ' ' '\n' | sed '/^$/d' |
#delete beginning ^$

sed "s/\`/'/g" |
#replace ` with '

tr A-Z a-z |
#Treat upper case as lower case

sed "/[^pkmnwlhaeiou']/d" |
#delete improperly formatted letter

sort -u
#sort the words
