#!/bin/bash

dir=$1

#get all the files in that route
HID=`ls -a $dir | grep '^\.' | sort`
NOR=`ls $dir | sort`

let cnt=0
declare -a ARRAY

#Get all hidden files

for HidF in $HID
do
      if [ -f "$dir/$HidF" ]
      then
            ARRAY[$cnt]="$dir/$HidF"
            let cnt=cnt+1
       fi
done

#Get all normal file
for NorF in $NOR
do
        if [ -f "$dir/$NorF" ]
        then
            ARRAY[$cnt]="$dir/$NorF"
            let cnt=cnt+1
     fi
done

for (( i=0; i<$cnt; i++ ))
do
    for (( j=i+1; j<$cnt; j++ ))
    do
        cmp -s "${ARRAY[$i]}" "${ARRAY[$j]}"
        if [ $? -eq 0 ]
        then
           rm "${ARRAY[$j]}"
           ln -fP  "${ARRAY[$i]}" "${ARRAY[$j]}"
	   ARRAY[$j]=ARRAY[$i]
        fi
    done
done
